"ui/resource/HudAmmo.res"
{
    "HudAmmoPanel"
    {
        "ControlName"                "CHudAmmoPanel"
        "fieldName"                  "HudAmmoPanel"
        "xpos"                       "r120"
        "ypos"                       "r35"
        "wide"                       "100"
        "tall"                       "24"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "0"
        "enabled"                    "1"
        "tabPosition"                "0"
        "PaintBackgroundType"        "2"

        "bgcolor_override"           "0 0 0 96"

        // Divider bar
        "divider_xpos"               "40"
        "divider_ypos"               "4"
        "divider_wide"               "2"
        "divider_tall"               "18"
        "divider_offcolor"           "128 128 128 96"

        // Resize bar when weapon has no clip
        "bar_shrink"               "1"
        "bar_wide"                 "60"
        "bar_full_wide"            "100"
        "bar_xpos"                 "r80"
        "bar_full_xpos"            "r120"

        // Ammo icon position
        "ammoicon_xpos"              "40"
        "ammoicon_full_xpos"         "80"
        "ammoicon_ypos"              "4"
        "ammoicon_wide"              "16"
        "ammoicon_tall"              "16"
    }
    "Clip"
    {
        "ControlName"                "Label"
        "fieldName"                  "Clip"
        "fgcolor_override"           "255 160 0 255"
        "xpos"                       "0"
        "ypos"                       "2"
        "wide"                       "36"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbersShadow"
        "labelText"                  "000"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
    "ClipGlow"
    {
        "ControlName"                "Label"
        "fieldName"                  "ClipGlow"
        "fgcolor_override"           "255 160 0 255"
        "xpos"                       "0"
        "ypos"                       "2"
        "wide"                       "36"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbersGlow"
        "labelText"                  "000"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
    "ClipBg"
    {
        "ControlName"                "Label"
        "fieldName"                  "ClipBg"
        "fgcolor_override"           "128 128 128 96"
        "xpos"                       "0"
        "ypos"                       "2"
        "wide"                       "36"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbers"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
    "Ammo"
    {
        "ControlName"                "Label"
        "fieldName"                  "Ammo"
        "fgcolor_override"           "255 160 0 255"
        "xpos"                       "36"
        "ypos"                       "2"
        "wide"                       "40"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbersShadow"
        "labelText"                  "000"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
    "AmmoGlow"
    {
        "ControlName"                "Label"
        "fieldName"                  "AmmoGlow"
        "fgcolor_override"           "255 160 0 255"
        "xpos"                       "36"
        "ypos"                       "2"
        "wide"                       "40"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbersGlow"
        "labelText"                  "000"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
    "AmmoBg"
    {
        "ControlName"                "Label"
        "fieldName"                  "AmmoBg"
        "fgcolor_override"           "128 128 128 96"
        "xpos"                       "36"
        "ypos"                       "2"
        "wide"                       "40"
        "tall"                       "20"
        "autoResize"                 "0"
        "pinCorner"                  "0"
        "RoundedCorners"             "15"
        "pin_corner_to_sibling"      "0"
        "pin_to_sibling_corner"      "0"
        "visible"                    "1"
        "enabled"                    "1"
        "tabPosition"                "0"
        "Font"                       "HudNumbers"
        "textAlignment"              "east"
        "dulltext"                   "0"
        "brighttext"                 "0"
        "wrap"                       "0"
        "centerwrap"                 "0"
        "textinsetx"                 "0"
        "textinsety"                 "0"
        "auto_wide_tocontents"       "0"
        "use_proportional_insets"    "0"
    }
}
